tasks:
- init: sudo apt update -y && sudo apt upgrade -y && python -m pip install --upgrade pip && pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens