tasks:
- init: sudo apt update && sudo apt upgrade -y && virtualenv venv && source venv/bin/activate && python -m pip install --upgrade pip wheel setuptools && pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.python
    - SonarSource.sonarlint-vscode
    - charliermarsh.ruff
    - eamodio.gitlens