name: archiver

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "5 2 * * *" # daily 2:05am UTC
  
  repository_dispatch: # run workflow on api request

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: clone this repo
        run: git clone https://github.com/tinyweatherforecastgermanygroup/TinyWeatherForecastGermanyArchiver "TinyWeatherForecastGermanyArchiver"
      
      - name: update packages
        run: sudo apt-get update && sudo apt-get upgrade
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: install virtualenv
        run: pip install virtualenv
      
      - name: list directory contents
        run: ls -lisha
      
      - name: init virtualenv
        run: virtualenv venv
      
      - name: activate virtualenv
        run: source venv/bin/activate
      
      - name: list directory contents
        run: ls -lisha

      - name: install python requirements
        run: pip install -r TinyWeatherForecastGermanyArchiver/requirements.txt
      
      - name: run async wayback machine archiver script
        run: timeout 5m python TinyWeatherForecastGermanyArchiver/__init__.py || true

      - name: list directory contents
        run: ls -lisha
