# This is a basic workflow to help you get started with Actions

name: archiver

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "5 2,18 * * *" # daily 2:05am UTC
  
  repository_dispatch: # run workflow on api request

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "archive"
  archive:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clone this repo
        run: git clone https://github.com/tinyweatherforecastgermanygroup/TinyWeatherForecastGermanyArchiver
      
      - name: update packages
        run: sudo apt-get update && sudo apt-get upgrade
      
      - name: Setup Python 3.x
        uses: actions/setup-python@v2.2.2
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: install virtualenv
        run: pip install virtualenv
      
      - name: list directory contents
        run: ls -lisha
      
      - name: init virtualenv
        run: virtualenv venv
      
      - name: activate virtualenv
        run: source venv/bin/activate
      
      - name: list directory contents
        run: ls -lisha

      - name: install python requirements
        run: pip install -r TinyWeatherForecastGermanyArchiver/requirements.txt
      
      - name: run wayback-machine-archiver
        run: archiver --file 'TinyWeatherForecastGermanyArchiver/urls.txt' --log DEBUG || true

      - name: list directory contents
        run: ls -lisha
